### ISSUE TITLE
Decoded token access from strategy+

### ISSUE THREAD

**Issue by teaglebuilt** [whitecloakph/nestjs-passport-firebase#10]
Is what ever is returned from the strategy available on the request? I was hoping to access the decoded token in the guard. is this possible?

**Comment by jimuelpalaca** [comment]
@teaglebuilt Yes.

The FirebaseStrategy `validate` method return value will be the `req.user` value when the `FirebaseAuthGuard` is used. And, by default, the `validate` method returns the DecodedIdToken - tho you can fully [customize](https://github.com/whitecloakph/nestjs-passport-firebase#customizing-firebase-strategy-validate-method) it.

Code Snippet:
```
  @Get('me')
  @UseGuards(FirebaseAuthGuard)
  async getAuthUserToken(@Request() req) {
    return req.user; // This will return the decoded token
  }
```

**Comment by jimuelpalaca** [comment]
I am closing this now. Feel free to reopen or submit a new issue if it still needs to be resolved. @teaglebuilt
