### ISSUE TITLE
Unable to resolve dependency tree - NestJS v8

### ISSUE THREAD

**Issue by david-vendel** [whitecloakph/nestjs-passport-firebase#4]
Hello, upon running npm install @whitecloak/nestjs-passport-firebase
I get:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: nest-typescript-starter@1.0.0
npm ERR! Found: @nestjs/common@8.2.3
npm ERR! node_modules/@nestjs/common
npm ERR!   @nestjs/common@"8.2.3" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @nestjs/common@"^7.6.7" from @whitecloak/nestjs-passport-firebase@1.0.2
npm ERR! node_modules/@whitecloak/nestjs-passport-firebase
npm ERR!   @whitecloak/nestjs-passport-firebase@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

What would be the solution for this?

**Comment by jimuelpalaca** [comment]
Hi @justdvl, I will add support for NestJS v8.

**Comment by moshtaghi** [comment]
@justdvl 
you can use it:
```
npm i @kakiueo/nestjs-passport-firebase
```

**Comment by jimuelpalaca** [comment]
Sorry guys, I've been busy this past few months. And, I am no longer part of White Cloak Technologies, Inc. I have already contacted the CTO (@xdgimf) and one of the backend leads, asking if they can continue the support of this package. 

Also, feel free to fork and submit a PR for the proposed solutions. Thanks!

@moshtaghi @justdvl

**Comment by jimuelpalaca** [comment]
@justdvl @moshtaghi 

[v1.0.3](https://github.com/whitecloakph/nestjs-passport-firebase/tree/v1.0.3) is up; closing this issue now. Kudos to sir @charlesuyso for maintaining.
